CC=g++
CFLAGS=-std=c++20

main: graph.h graph.cpp ford_fulkerson.h ford_fulkerson.cpp bfs.h bfs.cpp bfs_bi.h bfs_bi.cpp dijkstra.h dijkstra.cpp dijkstra_bi.h dijkstra_bi.cpp main.cpp
	$(CC) $(CFLAGS) -o main graph.cpp ford_fulkerson.cpp bfs.cpp bfs_bi.cpp dijkstra.cpp dijkstra_bi.cpp main.cpp
