CC=g++
CFLAGS=-std=c++20

main: graph.h graph.cpp dijkstra.h dijkstra.cpp bellman_ford.h bellman_ford.cpp moore_fifo_queue.h moore_fifo_queue.cpp moore.h moore.cpp main.cpp
	$(CC) $(CFLAGS) -o main graph.cpp dijkstra.cpp bellman_ford.cpp moore_fifo_queue.cpp moore.cpp main.cpp
