CC=g++
CFLAGS=-std=c++20

main: graph.h graph.cpp dijikstra.h dijikstra.cpp bellan_ford.h bellan_ford.cpp moore_fifo_queue.h moore_fifo_queue.cpp moore.h moore.cpp main.cpp
	$(CC) $(CFLAGS) -o main graph.cpp dijikstra.cpp bellan_ford.cpp moore_fifo_queue.cpp moore.cpp main.cpp
